# Generated by Django 3.1.6 on 2021-02-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desinations',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desinations',
            name='offere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='desinations',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
